site_name: Kota Kurihara - Portfolio
theme:
  name: material
  language: ja
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - i18n:
      languages:
        - locale: ja
          name: 日本語
          default: true
        - locale: en
          name: English
      reconfigure_material: true

# 404エラーを防ぐための設定
extra:
  directory_urls: false