site_name: 氏名 - ポートフォリオ
theme:
  name: material

# Markdown拡張（数式表示などを有効化）
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

# 日英切り替えの設定
plugins:
  - search
  - i18n:
      languages:
        - locale: ja
          name: 日本語
          default: true
        - locale: en
          name: English