site_name: 栗原昂汰
theme:
  name: material


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

# ▼▼ メニューバーを綺麗に整える設定 ▼▼
nav:
  - Home: index.md
  - Publications: publications.md

# ▼▼ 言語設定 ▼▼
plugins:
  - search
  - i18n:
      languages:
        - locale: ja
          name: 日本語
          default: true
        - locale: en
          name: English